inputSet:
  identifier: "is2"
  name: "is2"
  orgIdentifier: "default"
  projectIdentifier: "nofar_dinesh"
  pipeline:
    identifier: "pipeline1"
    stages:
    - stage:
        identifier: "S1"
        type: "CI"
        spec:
          execution:
            steps:
            - step:
                identifier: "echo"
                type: "Run"
                spec:
                  image: "maven"
