pipeline:
    name: Jave Demo
    identifier: Jave_Demo
    projectIdentifier: nofar_dinesh
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.shivagowdawings
                repoName: jhttp
                build: <+input>
    stages:
        - stage:
              name: Build Test and Push
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                timeout: 2h
                                name: Run Tests With Tests Intelligence
                                identifier: Run_Tests_With_Tests_Intelligence
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: maven:3.5.2-jdk-8-alpine
                                    args: test
                                    buildTool: maven
                                    language: java
                                    packages: io.harness.
                                    runOnlySelectedTests: true
                                    postCommand: mvn clean package -DskipTests
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    resources:
                                        limits:
                                            memory: 1000Mi
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and push image to DockerHub
                                timeout: 2h
                                identifier: Build_and_push_image_to_DockerHub
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    repo: bluebbb/javademo
                                    tags:
                                        - <+pipeline.sequenceId>
                          - step:
                                type: Run
                                name: Create Ticket
                                identifier: Create_Ticket
                                spec:
                                    connectorRef: harnessImage
                                    image: alpine
                                    command: echo "jira"
                                    privileged: false
                                when:
                                    stageStatus: Failure
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.pmdemonofar
                          namespace: harness-delegate-pm
                  serviceDependencies: []
                  sharedPaths:
                      - ""
              variables:
                  - name: myStageVar
                    type: String
                    value: stageVarValue
        - stage:
              name: Run Integration Test
              identifier: Run_Integration_Test
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test connection to server
                                identifier: test_connection_to_server
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: curlimages/curl:7.69.1
                                    command: |-
                                        sleep 5
                                        curl localhost:8888
                  serviceDependencies:
                      - identifier: runhelloworldserver
                        name: Run Hello World Server
                        type: Service
                        spec:
                            connectorRef: account.nofar_dockerhub
                            image: bluebbb/javademo:<+pipeline.sequenceId>
                  infrastructure:
                      useFromStage: Test_Build_and_Push
                  sharedPaths:
                      - ""
              description: running integ tests
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
